### ISSUE TITLE
Show graph of kc/xp over time per tile when clicked

### ISSUE THREAD

**Issue by Grieve-r** [Odinnh/osrs-bingo#3]
When you click on a tile, show a graph of XP gained/KC gained by each team, and add highest XP/KC gained by player with a toggle button (as to not make the graph cluttered)

**Comment by Qrollop** [comment]
Pull Data Straight from WOM? Potential issue: WOM not updated. Have it click update like every 3h on participants? idk

**Comment by Grieve-r** [comment]
one of the requirements of the bingo is to set up auto WOM updating with the plugin, so the only problem would be mobile users.

Maybe a manual button that can be pushed once every x hours? That way we aren't spamming their API and risking a rate limit?

**Comment by Odinnh** [comment]
the WOM api might face some difficulties though ill see what i can do with it...

**Comment by Odinnh** [comment]
there is hope, i found a hook to interface with WOM, so a generall WOM intergration seems plausible
